# Generated by Django 5.2.6 on 2025-09-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('service_description', models.TextField()),
                ('service_image', models.ImageField(blank=True, upload_to='services/')),
            ],
        ),
    ]
