# Generated by Django 5.2.6 on 2025-09-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_image',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
